In [1]:
import tifffile

In [2]:
original_image = "../data/inputs-2020-07/BF-C2DL-MuSC/KIT-Sch-GE/01_RES/mask0000.tif"
synced_image = "../data/synchronized_data/BF-C2DL-MuSC/KIT-Sch-GE/01_RES/mask0000.tif"

In [3]:
or_image = tifffile.imread(original_image)
sync_image = tifffile.imread(synced_image)

In [4]:
or_image

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1036, 1070), dtype=uint16)

In [5]:
sync_image

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1036, 1070), dtype=uint16)

In [6]:
import numpy as np

In [7]:
np.unique(or_image)

array([0, 1], dtype=uint16)

In [8]:
np.unique(sync_image)

array([0, 1], dtype=uint16)

In [9]:
or_image == sync_image

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]],
      shape=(1036, 1070))

In [10]:
import os
from PIL import Image
import numpy as np
import tifffile

# File paths
original_file = "../data/inputs-2020-07/BF-C2DL-MuSC/KIT-Sch-GE/01_RES/mask0000.tif"
processed_file = "../data/synchronized_data/BF-C2DL-MuSC/KIT-Sch-GE/01_RES/mask0000.tif"

def analyze_tif(file_path):
    # Basic file info
    file_size = os.path.getsize(file_path) / (1024 * 1024)  # Size in MB
    
    # Using PIL
    with Image.open(file_path) as img:
        mode = img.mode
        size = img.size
        format_info = img.format_description
        
    # Using tifffile for more detailed TIFF info
    with tifffile.TiffFile(file_path) as tif:
        compression = tif.pages[0].compression
        dtype = tif.pages[0].dtype
        is_bigtiff = tif.is_bigtiff
        tags = {tag.name: tag.value for tag in tif.pages[0].tags}
    
    return {
        "File Size (MB)": file_size,
        "Dimensions": size,
        "Mode": mode,
        "Format": format_info,
        "Compression": compression,
        "Data Type": dtype,
        "Is BigTIFF": is_bigtiff,
        "Bit Depth": 8 if 'uint8' in str(dtype) else 16 if 'uint16' in str(dtype) else 32,
        "Tags": tags
    }

# Compare files
original_info = analyze_tif(original_file)
processed_info = analyze_tif(processed_file)

# Display comparison
print("=== ORIGINAL FILE ===")
for key, value in original_info.items():
    if key != "Tags":  # Skip full tags display for brevity
        print(f"{key}: {value}")

print("\n=== PROCESSED FILE ===")
for key, value in processed_info.items():
    if key != "Tags":  # Skip full tags display for brevity
        print(f"{key}: {value}")

# Show differences
print("\n=== DIFFERENCES ===")
for key in original_info:
    if key != "Tags" and original_info[key] != processed_info[key]:
        print(f"{key}: {original_info[key]} → {processed_info[key]}")

=== ORIGINAL FILE ===
File Size (MB): 0.04528045654296875
Dimensions: (1070, 1036)
Mode: I;16
Format: Adobe TIFF
Compression: 5
Data Type: uint16
Is BigTIFF: False
Bit Depth: 16

=== PROCESSED FILE ===
File Size (MB): 2.1145496368408203
Dimensions: (1070, 1036)
Mode: I;16B
Format: Adobe TIFF
Compression: 1
Data Type: uint16
Is BigTIFF: False
Bit Depth: 16

=== DIFFERENCES ===
File Size (MB): 0.04528045654296875 → 2.1145496368408203
Mode: I;16 → I;16B
Compression: 5 → 1
