In [10]:
tracking_files_dir = "../data/inputs-2020-07/BF-C2DL-HSC/01_GT/TRA/*.tif"
gt_files_dir = "../data/inputs-2020-07/BF-C2DL-HSC/01_GT/SEG/*"

In [11]:
# Logic would serve, that comparison between ground truth and tracking markers will be perfect

In [12]:
from glob import glob

In [14]:
tracking_files = glob(tracking_files_dir)

In [ ]:
# we only care about the numbers in the file names. Those should be mapped to each other.
tracking_files

In [18]:
tracking_files[0]

'../data/inputs-2020-07/BF-C2DL-HSC/01_GT/TRA/man_track1357.tif'

In [20]:
import pathlib

In [21]:
pathlib.Path(tracking_files[0]).stem

'man_track1357'

In [22]:
import re

In [30]:
re.sub('[\D\s]', '', 'man_track1357')

'1357'

In [36]:
import tifffile
import numpy as np

In [37]:
track_file = tifffile.imread(tracking_files[0])

In [38]:
np.unique(track_file)

array([ 0, 26, 27, 31, 33, 34, 36, 57, 59], dtype=uint16)

In [39]:
gt_files = glob(gt_files_dir)

In [42]:
gt_file = tifffile.imread("../data/inputs-2020-07/BF-C2DL-HSC/01_GT/SEG/man_seg1357.tif")

In [43]:
np.unique(gt_file)

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=uint16)

In [45]:
gt_file_synced = tifffile.imread("../data/inputs-2020-07/BF-C2DL-HSC/01_GT_sync/man_seg1357.tif")

In [46]:
np.unique(gt_file_synced)

array([ 0, 26, 27, 31, 33, 34, 36, 57, 59], dtype=uint16)

In [ ]:
track_file = tifffile.imread(g[0])